#!/usr/bin/env node
/**
 * Copies the framework-free modules the web app and this app share (API types, zod schemas,
 * formatting, catalogue, realtime wire protocol) from ../phenko-mat-web into src/shared/.
 *
 * The web repo is the source of truth. Run `pnpm sync:shared` after changing any of these there;
 * never edit src/shared/* by hand. (Moving both apps into one pnpm workspace with a `@phenko/shared`
 * package is the natural next step once they share a repo.)
 */
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const web = resolve(root, process.env.WEB_APP_DIR ?? "../phenko-mat-web");
const out = resolve(root, "src/shared");

const FILES = {
  "lib/dto.ts": "dto.ts",
  "lib/validation.ts": "validation.ts",
  "lib/format.ts": "format.ts",
  "lib/catalog.ts": "catalog.ts",
  "lib/realtime/protocol.ts": "protocol.ts",
  "lib/site.ts": "site.ts",
};

const HEADER = "// GENERATED by scripts/sync-shared.mjs from phenko-mat-web — do not edit here.\n";

mkdirSync(out, { recursive: true });
for (const [from, to] of Object.entries(FILES)) {
  const source = readFileSync(resolve(web, from), "utf8");
  writeFileSync(resolve(out, to), HEADER + source);
  console.log(`synced ${from} → src/shared/${to}`);
}
