#!/usr/bin/env node
/**
 * Copies the database schema from ../phenko-mat-web (the source of truth, which also owns the
 * migrations) into db/schema.ts. Run `pnpm sync:schema` after the web app changes its schema;
 * never edit db/schema.ts by hand, and never run migrations from this app.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const web = resolve(root, process.env.WEB_APP_DIR ?? "../phenko-mat-web");
const source = readFileSync(resolve(web, "db/schema.ts"), "utf8");
writeFileSync(
  resolve(root, "db/schema.ts"),
  "// GENERATED by scripts/sync-schema.mjs from phenko-mat-web — do not edit here.\n" + source,
);
console.log("synced db/schema.ts");
