// GENERATED by scripts/sync-shared.mjs from phenko-mat-web — do not edit here.
import { z } from "zod";

/*
 * Request schemas shared by the API (authoritative) and the forms (for instant feedback).
 * Limits mirror the DB constraints in db/schema.ts.
 */

// Strip control characters (keeps newlines/tabs) so stored text can't carry invisible payloads.
const clean = (s: string) => s.replace(/[\u0000-\u0008\u000B\u000C\u000E-\u001F\u007F​-‏‪-‮]/g, "").trim();

const text = (min: number, max: number, label: string) =>
  z
    .string()
    .transform(clean)
    .pipe(
      z
        .string()
        .min(min, min === 1 ? `${label} is required.` : `${label} must be at least ${min} characters.`)
        .max(max, `${label} must be at most ${max} characters.`),
    );

export const CONDITIONS = ["new", "like_new", "good", "used"] as const;
export const conditionSchema = z.enum(CONDITIONS);

export const categoryIdSchema = z
  .string()
  .regex(/^[a-z0-9]+(?:-[a-z0-9]+)*$/, "Invalid category.")
  .max(48);

export const photoUrlSchema = z.url({ protocol: /^https$/ }).max(1000);

export const locationSchema = z.object({
  lat: z.number().min(-90).max(90),
  lng: z.number().min(-180).max(180),
  area: text(2, 80, "Area"),
});

export const itemCreateSchema = z.object({
  title: text(3, 80, "Title"),
  description: text(0, 1000, "Description").default(""),
  photos: z.array(photoUrlSchema).min(1, "Add at least one photo.").max(6, "Up to 6 photos."),
  categoryIds: z
    .array(categoryIdSchema)
    .min(1, "Pick at least one category.")
    .max(5, "Pick up to 5 categories.")
    .transform((ids) => [...new Set(ids)]),
  condition: conditionSchema,
  // No free listings: anything from ₹1.
  priceInr: z.number().int().min(1, "Price must be at least ₹1.").max(10_000_000),
  /** Where the item is picked up. Omitted: the owner's profile location. Others only ever see the area. */
  location: locationSchema.optional(),
});
export type ItemCreateInput = z.infer<typeof itemCreateSchema>;

export const itemUpdateSchema = itemCreateSchema
  .partial()
  .extend({
    status: z.enum(["active", "given"]).optional(),
    /** With `status: "given"`: the person (who connected on this item) who got it; null if someone else. */
    givenToId: z.uuid().nullable().optional(),
  })
  .refine((v) => v.givenToId === undefined || v.status === "given", "givenToId needs status \"given\".")
  .refine((v) => Object.keys(v).length > 0, "Nothing to update.");


export const profileUpdateSchema = z
  .object({
    name: text(1, 60, "Name"),
    bio: text(0, 300, "Bio"),
    avatarUrl: photoUrlSchema.nullable(),
    location: locationSchema,
    radiusKm: z.number().int().min(1).max(100),
    interests: z.array(categoryIdSchema).max(30).transform((ids) => [...new Set(ids)]),
  })
  .partial()
  .refine((v) => Object.keys(v).length > 0, "Nothing to update.");

export const swipeSchema = z.object({
  itemId: z.uuid(),
  direction: z.enum(["left", "right"]),
});

export const messageSchema = z.object({
  body: text(1, 2000, "Message"),
  /** Idempotency key generated by the client (retries never duplicate a message). */
  clientId: z.uuid(),
});

export const categoryCreateSchema = z.object({
  name: text(2, 40, "Name").pipe(z.string().regex(/^[\p{L}\p{N} &'\-]+$/u, "Use letters, numbers, spaces, & or -.")),
  emoji: z
    .string()
    .trim()
    .min(1)
    .max(16)
    .regex(/^\p{Extended_Pictographic}/u, "Pick an emoji."),
});

export const reportSchema = z.object({
  reason: z.enum(["spam", "scam", "prohibited", "offensive", "other"]),
  details: text(0, 500, "Details").optional(),
});

export const placesQuerySchema = z.object({
  q: text(2, 100, "Search"),
  /** Groups the typing + the final pick into one billed session (Google session tokens). */
  session: z.string().min(8).max(64),
  lat: z.coerce.number().min(-90).max(90).optional(),
  lng: z.coerce.number().min(-180).max(180).optional(),
});

export const placeDetailsQuerySchema = z.object({
  session: z.string().min(8).max(64),
});

/** A spot picked on the map, to be named ("Koregaon Park, Pune"). */
export const reverseGeocodeQuerySchema = z.object({
  lat: z.coerce.number().min(-90).max(90),
  lng: z.coerce.number().min(-180).max(180),
});

/** Batched from the deck: cards that reached the top, and cards whose details were opened. */
export const viewsSchema = z.object({
  seen: z.array(z.uuid()).max(50).default([]),
  details: z.array(z.uuid()).max(50).default([]),
});

export const feedQuerySchema = z.object({
  category: categoryIdSchema.optional(),
  scope: z.enum(["nearby", "all"]).default("nearby"),
  /** Free-text search over title, description and category names (typo tolerant). */
  q: text(1, 80, "Search").optional(),
  limit: z.coerce.number().int().min(1).max(30).default(20),
});

export const messagesQuerySchema = z
  .object({
    /** Polling: messages newer than this id. */
    after: z.coerce.number().int().min(0).optional(),
    /** Scrolling back: the page of messages older than this id. */
    before: z.coerce.number().int().min(1).optional(),
  })
  .refine((q) => q.after === undefined || q.before === undefined, "Use either after or before.");

export const sessionSchema = z.object({
  idToken: z.string().min(20).max(4096),
});

/** A crash or error report from the web or mobile client (admin Errors page). */
export const clientErrorSchema = z.object({
  source: z.enum(["web", "mobile"]),
  message: z.string().trim().min(1).max(1000),
  stack: z.string().max(8000).optional(),
  /** Page path or screen name where it happened. */
  route: z.string().max(200).optional(),
  /** Platform, OS, app version, user agent… (short strings only). */
  meta: z.record(z.string().max(40), z.union([z.string().max(300), z.number(), z.boolean()])).optional(),
});
